export const STATUS_SAFRA_PROJETO = ["PLANEJADO", "EM_ANDAMENTO", "ENCERRADO"] as const;

export const TIPO_CONTA_BANCARIA = [
  "CORRENTE",
  "APLICACAO",
  "INVESTIMENTO",
  "EMPRESTIMO_FINANCIAMENTO",
] as const;

export const TIPO_CATEGORIA_FINANCEIRA = ["RECEITA", "DESPESA"] as const;

export const TIPO_TITULO = ["PAGAR", "RECEBER"] as const;

export const STATUS_PARCELA = [
  "EM_ABERTO",
  "A_VENCER",
  "VENCIDO",
  "PARCIALMENTE_PAGO",
  "PAGO",
  "CANCELADO",
  "RENEGOCIADO",
] as const;

export const STATUS_APROVACAO_BAIXA = ["PENDENTE", "APROVADO", "REJEITADO"] as const;
